<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">


    <!-- Bootstrap core CSS -->
    <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

            {
            box-sizing: border-box;
        }

        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        /* The Modal (background) */
        .modal {
            display: none;
            /* Hidden by default */
            position: fixed;
            /* Stay in place */
            z-index: 1;
            /* Sit on top */
            padding-top: 100px;
            /* Location of the box */
            left: 0;
            top: 0;
            width: 100%;
            /* Full width */
            height: 100%;
            /* Full height */
            overflow: auto;
            /* Enable scroll if needed */
            background-color: rgb(0, 0, 0);
            /* Fallback color */
            background-color: rgba(0, 0, 0, 0.4);
            /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
        }

        /* The Close Button */
        .close {
            color: #aaaaaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: #000;
            text-decoration: none;
            cursor: pointer;
        }

        /* body {
  font-family: Arial, sans-serif;
  background: url(http://www.shukatsu-note.com/wp-content/uploads/2014/12/computer-564136_1280.jpg) no-repeat;
  background-size: cover;
  height: 100vh;
} */

h1 {
  text-align: center;
  font-family: Tahoma, Arial, sans-serif;
  color: #06D85F;
  margin: 80px 0;
}

.box {
  width: 40%;
  margin: 0 auto;
  background: rgba(255,255,255,0.2);
  padding: 35px;
  border: 2px solid #fff;
  border-radius: 20px/50px;
  background-clip: padding-box;
  text-align: center;
}

.button {
  font-size: 1em;
  padding: 10px;
  color: #fff;
  border: 2px solid #06D85F;
  border-radius: 20px/50px;
  text-decoration: none;
  cursor: pointer;
  transition: all 0.3s ease-out;
}
.button:hover {
  background: #06D85F;
}

.overlay {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.7);
  transition: opacity 500ms;
  visibility: hidden;
  opacity: 0;
}
.overlay:target {
  visibility: visible;
  opacity: 1;
}

.popup {
  margin: 70px auto;
  padding: 20px;
  background: #fff;
  border-radius: 5px;
  width: 30%;
  position: relative;
  transition: all 5s ease-in-out;
}

.popup h2 {
  margin-top: 0;
  color: #333;
  font-family: Tahoma, Arial, sans-serif;
}
.popup .close {
  position: absolute;
  top: 20px;
  right: 30px;
  transition: all 200ms;
  font-size: 30px;
  font-weight: bold;
  text-decoration: none;
  color: #333;
}
.popup .close:hover {
  color: #06D85F;
}
.popup .content {
  max-height: 30%;
  overflow: auto;
}

@media screen and (max-width: 700px){
  .box{
    width: 70%;
  }
  .popup{
    width: 70%;
  }
}

    </style>


    <!-- Custom styles for this template -->
    <link href="./assets/css/dashboard.css" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>


    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a class="nav-link px-3" href="sess">Sign out</a>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="http://localhost:8080/product/add">
                                <span data-feather="home"></span>
                                ADD NEW PRODUCT
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Products</h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group me-2">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                            <span data-feather="calendar"></span>
                            This week
                        </button>
                    </div>
                </div>
                <form method="POST" action="/product/displayproducts">
               <input type="text" placeholder="Search here" name="name">
               <input type="submit" name="search" value="SEARCH">
                   
                </form>

                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>

                                <th scope="col">NAME</th>
                                <th scope="col">CATEGORY NAME</th>
                                <th scope="col">PRICE</th>
                                <th scope="col">STOCK</th>
                                <th scope="col">TAGS</th>
                                <th scope="col">VIEW</th>
                                <th scope="col">EDIT</th>
                                <th scope="col">DELETE</th>

                            </tr>
                        </thead>
                        <tbody>
                            <?php

                            if (isset($v)) {
                                $html = "";
                                $html .= '<form method="POST" action="access"<tr>
                                <td>' . $v['Details']['name'] . '</td>
                                <td>' . $v['Details']['categoryname'] . '</td>
                                <td>' . $v['Details']['price'] . '</td>
                               <td>' . $v['Details']['stock'] . '</td>
                                <td>' . $v['Details']['tags'] . '</td>
                                <td><a href="#'.$v['_id']['$oid'].'">VIEW</a> </td>
                                <td><a href="editproduct?id=' . $v['_id']['$oid'] . '">EDIT</a> </td>
                                <td><a href="deleteproduct?id=' . $v['_id']['$oid'] . '">DELETE</a> </td>
                            </tr></form>';?>

                            <div id="<?php echo $v['_id']['$oid']; ?>" class="overlay">
                            <div class="popup">
                                <h1><?php echo $v['Details']['name']; ?></h1>
                                <a class="close" href="#">&times;</a>
                                <div class="content">
                                    <h3>META FEILDS</h3>
                                    <?php 
                                    foreach($v['Additional Fields'] as $p=>$q){
                                    echo $p." " ;
                                    echo $q;
                                    echo "<br>";
                                    }
                                    ?>
                                    <br>
                                    <h3>VARIATIONS</h3>
                                    <?php 
                                    foreach($v['Variations'] as $p=>$q){
                                   
                                    echo $q[0]." ";
                                    echo $q[1]." ";
                                    echo $q[2]." ";
                                    echo $q[3]." ";
                                    echo "Price: ".$q[4]." ";
                                    echo "<br>";
                                    }
                                    

                            } else {

                            $result = $this->mongo->product->find();
                            // $result=json_decode($result, true);
                            $html = "";
                            foreach ($result as $v) {
                                $v = json_decode(json_encode($v, true), true);
                                //  echo "<pre>";
                                //  print_r($v);
                                //  die;
                                $html .= '<form method="POST" action="access"<tr>
               <td>' . $v['Details']['name'] . '</td>
               <td>' . $v['Details']['categoryname'] . '</td>
               <td>' . $v['Details']['price'] . '</td>
              <td>' . $v['Details']['stock'] . '</td>
               <td>' . $v['Details']['tags'] . '</td>
               <td><a href="#'.$v['_id']['$oid'].'">VIEW</a> </td>
               <td><a href="editproduct?id=' . $v['_id']['$oid'] . '">EDIT</a> </td>
               <td><a href="deleteproduct?id=' . $v['_id']['$oid'] . '">DELETE</a> </td>
           </tr></form>';?>

           <div id="<?php echo $v['_id']['$oid']; ?>" class="overlay">
	<div class="popup">
		<h1><?php echo $v['Details']['name']; ?></h1>
		<a class="close" href="#">&times;</a>
		<div class="content">
			<h3>META FEILDS</h3>
            <?php 
            foreach($v['Additional Fields'] as $p=>$q){
            echo $p." " ;
            echo $q;
            echo "<br>";
            }
            ?>
            <br>
            <h3>VARIATIONS</h3>
            <?php 
            foreach($v['Variations'] as $p=>$q){
           
            echo $q[0]." ";
            echo $q[1]." ";
            echo $q[2]." ";
            echo $q[3]." ";
            echo "Price: ".$q[4]." ";
            echo "<br>";
            }
            ?>
            <br>
		</div>
	</div>
</div><?php 
                            }
                        }
                            $html .= "";
                            echo $html;
                          ?>




                            <script>
                                // Get the modal
                                var modal = document.getElementById("myModal");

                                // Get the button that opens the modal
                                var btn = document.getElementById("myBtn");

                                // Get the <span> element that closes the modal
                                var span = document.getElementsByClassName("close")[0];

                                // When the user clicks the button, open the modal 
                                btn.onclick = function() {
                                    modal.style.display = "block";
                                }

                                // When the user clicks on <span> (x), close the modal
                                span.onclick = function() {
                                    modal.style.display = "none";
                                }

                                // When the user clicks anywhere outside of the modal, close it
                                window.onclick = function(event) {
                                    if (event.target == modal) {
                                        modal.style.display = "none";
                                    }
                                }
                            </script>
</body>

</html>